module "profile_kids" {
  source       = "../../terraform-modules/profile"
  profile_name = "Kids"
}


resource "nextdns_parental_control" "kids" {
  profile_id = module.profile_kids.id

  # Safe Search
  # Filter explicit results on all major search engines, including images and videos. This will also block access to search engines not supporting this feature.
  safe_search = true

  # YouTube Restricted Mode
  # Filter out mature videos on YouTube and block embedded mature videos from being watched on other websites. This will also hide all comments.
  youtube_restricted_mode = true

  # Block bypass
  # Prevent or hinder the use of methods that can help bypass NextDNS filtering on the network. This includes VPNs, proxies, Tor-related software and encrypted DNS providers.
  block_bypass = true

  # Restrict access to specific websites, apps and games.
  # service {
  #   id         = "facebook"
  #   active     = true
  #   recreation = true
  # }


  # Category
  # Restrict access to specific categories of websites and apps.
  #
  category {
    id         = "porn"
    active     = true
    recreation = false
  }

  category {
    id         = "gambling"
    active     = true
    recreation = false
  }

  category {
    id         = "dating"
    active     = false
    recreation = false
  }

  category {
    id         = "piracy"
    active     = true
    recreation = false
  }

  category {
    id         = "social-networks"
    active     = true
    recreation = false
  }

  category {
    id         = "online-gaming"
    active     = true
    recreation = false
  }

  category {
    id         = "video-streaming"
    active     = false
    recreation = false
  }


  # Recreation Time
  # Set a period for each day of the week during which some of the websites, apps, games or categories above will not be blocked — e.g. allow Facebook on Mondays and Tuesdays between 6pm and 8pm.
  # recreation {
  #   timezone = "America/New_York"

  #   monday {
  #     start = "07:02:00"
  #     end   = "23:00:00"
  #   }
  # }
}

resource "nextdns_security" "kids" {
  profile_id = module.profile_kids.id

  /**
  Threat Intelligence Feeds
  Block domains known to distribute malware, launch phishing attacks and host command-and-control servers using a blend of the most reputable threat intelligence feeds — all updated in real-time.
  **/
  threat_intelligence_feeds = true

  /**
  AI-Driven Threat Detection
  Block millions of threats detected by our AI technology — a proprietary AI engine designed from the ground up for DNS with hundreds of signals, terabytes of training data and real-time decision making.
  **/
  ai_threat_detection = false

  /**
  Google Safe Browsing
  Block malware and phishing domains using Google Safe Browsing — a technology that examines billions of URLs per day looking for unsafe websites. Unlike the version embedded in some browsers, this does not associate your public IP address to threats and does not allow bypassing the block.
  **/
  google_safe_browsing = true

  /**
  Cryptojacking Protection
  Prevent the unauthorized use of your devices to mine cryptocurrency.
  **/

  crypto_jacking = true

  /**
  DNS Rebinding Protection
  Prevent attackers from taking control of your local devices through the Internet by automatically blocking DNS responses containing private IP addresses.
  **/
  dns_rebinding = true

  /**
  IDN Homograph Attacks Protection
  Block domains that impersonate other domains by abusing the large character set made available with the arrival of Internationalized Domain Names (IDNs) — e.g. replacing the Latin letter "e" with the Cyrillic letter "е".
  **/
  idn_homographs = true

  /**
  Typosquatting Protection
  Block domains registered by malicious actors that target users who incorrectly type a website address into their browser — e.g. gooogle.com instead of google.com.
  **/

  typo_squatting = true

  /**
  Domain Generation Algorithms (DGAs) Protection
  Block domains generated by Domain Generation Algorithms (DGAs) seen in various families of malware that can be used as rendezvous points with their command and control servers.
  **/
  dga = true

  /**
  Block Newly Registered Domains (NRDs)
  Block domains registered less than 30 days ago. Those domains are known to be favored by threat actors to launch malicious campaigns.
  **/
  nrd = true

  /**
  Block Dynamic DNS Hostnames
  Dynamic DNS (or DDNS) services let malicious actors quickly set up hostnames for free and without any validation or identity verification. While legit DDNS hostnames are rarely accessed in every-day use, their malicious counterparts are heavily used in phishing campaigns — e.g. paypal‑login.duckdns.org.
  If you are using DDNS, note that this setting will not block the DDNS services' own website or their update API.
  **/
  ddns = true

  /**
  Block Parked Domains
  Parked domains are single-page websites often laden with ads and devoid of any value. Parked domain monetization can sometimes get mixed up with suspicious practices and malicious content.
  **/
  parking = true

  /**
  Block Child Sexual Abuse Material
  Block domains hosting child sexual abuse material with the help of Project Arachnid, operated by the Canadian Centre for Child Protection. No information is transmitted back to Project Arachnid when a domain is blocked.
  **/
  csam = true

  /**
  Block Top-Level Domains (TLDs)
  Block all domains and subdomains belonging to specific TLDs.
  **/
  tlds = toset([])
}

resource "nextdns_privacy" "kids" {
  profile_id = module.profile_kids.id

  # Block Disguised Third-Party Trackers
  # Automatically detect and block third-party trackers disguising themselves as first-party to circumvent recent browser's privacy protections like ITP.
  disguised_trackers = true

  # Allow Affiliate & Tracking Links
  # Allow affiliate & tracking domains common on deals websites, in emails or in search results. Those usually only get called after manually clicking on a link.
  allow_affiliate = false

  # Blocklists
  # Block ads & trackers using the most popular blocklists available — all updated in real-time.
  blocklists = toset([
    "nextdns-recommended",
  ])

  # Native Tracking Protection
  # Block wide spectrum trackers — often operating at the operating system level — that track your activity on a device. This could include all the websites you visit, everything you type or your location at all times.
  natives = toset([
    "apple",
    "alexa",
    "samsung",
  ])
}

resource "nextdns_settings" "kids" {
  profile_id = module.profile_kids.id

  logs {
    enabled = true

    privacy {
      log_clients_ip = true
      log_domains    = true
    }

    retention = "1 week"
    location  = "ch"
  }

  # Block Page
  # Display a block page when a domain is being blocked. This may slightly increase page load time and an HTTPS warning may appear in some cases. When disabled, blocked queries will be answered with the unspecified address (0.0.0.0 or ::).
  block_page {
    enabled = true
  }

  performance {
    # Anonymized EDNS Client Subnet
    # Speed up the delivery of data from content delivery networks without exposing your IP address.
    ecs = true

    # Cache Boost
    # Minimize DNS queries by enforcing a minimum TTL (Time to live).
    cache_boost = true

    # CNAME Flattening
    # Prevent CNAME-chasing resolvers from making unnecessary queries and pollute the logs with intermediate domains.
    cname_flattening = true
  }

  # Web3
  # Web3 refers to a decentralized and censorship-resistant online ecosystem comprised of innovative technologies such as blockchain-based domain registries (e.g. Ethereum Name Service) and distributed content storage and delivery networks (e.g. IPFS). When enabled, NextDNS will act as an unfiltered gateway to this new Web, letting you experience it firsthand without the need to install anything.
  # As most browsers only support classic top-level domains at the moment, you should add a trailing slash ("/") when trying to access a Web3 domain directly (e.g. "vitalik.eth/" instead of "vitalik.eth").
  web3 = false
}
